### ISSUE TITLE
Registered S3 method overwritten by 'R2WinBUGS':

### ISSUE THREAD

**Issue by skhan-math-uw** [datacloning/dclone#14]
jags.parfit does not work without R2WinBUGS. If R2WinBUGS is not installed, it gives "Error in loadNamespace(name) : there is no package called ‘R2WinBUGS’". It works if R2WinBUGS is installed, though it shows the message

Registered S3 method overwritten by 'R2WinBUGS':
  method            from  
  as.mcmc.list.bugs dclone

the first time I run jags.parfit.

**Comment by psolymos** [comment]
I think the error is related to `jags.parfit` using `R2WinBUGS::write.model` when the model is supplied as a character vector or function. I will investigate further.
