### ISSUE TITLE
Error: Port cannot be open

### ISSUE THREAD

**Issue by DiogoFerrari** [datacloning/dclone#6]
I am running different R scripts in batch mode at once in a linux cluster to estimate a model in different data sets (it also happens when I run it in Mac). The scripts are exactly the same, except for the data set that they are using. I get the following message when I do that.

Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  : 
  cannot open the connection
Calls: makePSOCKcluster -> newPSOCKnode -> socketConnection
In addition: Warning message:
In socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  :
  port 11426 cannot be opened

Here is a reproducible example. Create two files, tmp1.R and tmp2.R, and tmp.sh with the content:
- Content of the files tmp1.R and tmp2.R:
  library(dclone)
  l <- list(1:100,1:100,1:100,1:100)
  cl <- makePSOCKcluster(4)
  parLapply(cl, X=l, fun=function(x) {Sys.sleep(2); sum(x); })
  stopCluster(cl)
- Content of the tmp.sh file:
  # !/bin/sh
  
  R CMD BATCH tmp1.R &
  R CMD BATCH tmp2.R &

The first file in the list will be executed. The second will present the error above. Does anyone know how to solve it and still run all the scripts at once automatically without any manual intervention?

**Comment by psolymos** [comment]
Have you tried quitting your R session? Close the file with q('no')

**Comment by DiogoFerrari** [comment]
I am not sure if I understood the question, but the two scripts run at the same time in batch mode. They both start before the other is finished, that is, before any statement as "q('n')".

**Comment by psolymos** [comment]
I see. Now it makes sense. This way you start 2 master processes that spawn the child processes, and the 2nd master's children are in conflict with the 1st ones.

I also don't think it is a dclone problem, the same should happen if you replace the 1st line with `library(parallel)`. I tried both dclone and parallel multiple times, and sometimes both exited fine (without error), sometimes tmp2.R finished but tmp1.R gave error, etc. So I really do think it is the double master process causing trouble.

**Comment by DiogoFerrari** [comment]
That was my guess too, although I thought it could be resolved via manipulation of parameters of functions of the package, or using some workaround. I have seen many posts about the problem, but no clear solution yet.
